[project]
name = "sound-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aleksa Dejanovic", email = "dejanovicaleksa234@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "allosaurus>=1.0.2",
    "numba<0.60",
    "numpy==1.26.4",
    "panphon==0.21.2",
    "resampy==0.4.3",
    "setuptools<81",
    "sounddevice>=0.5.5",
]

[project.scripts]
sound-analyzer = "sound_analyzer:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
